Feature: Chord Reveal (Middle-click reveal)
  As a player
  I want to be able to chord reveal around numbered cells
  So that I can quickly reveal multiple cells when I've correctly flagged all adjacent mines

  Background:
    Given I want to start a new game

  Scenario: Chord reveal with correct flags reveals adjacent cells
    Given the board is:
      """
      *........
      .........
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I chord reveal cell at row 1, column 0
    Then the cells at (0,1), (1,1), (2,0), (2,1) should be revealed
    And the game state should be "playing"

  Scenario: Chord reveal with incorrect number of flags does nothing
    Given the board is:
      """
      *........
      .........
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I chord reveal cell at row 1, column 0
    Then the cell at row 0, column 1 should not be revealed
    And the game state should be "playing"

  Scenario: Chord reveal with too many flags does nothing
    Given the board is:
      """
      *........
      .........
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I flag cell at row 0, column 1
    And I chord reveal cell at row 1, column 0
    Then the cell at row 0, column 2 should not be revealed
    And the game state should be "playing"

  Scenario: Chord reveal on unrevealed cell does nothing
    Given the board is:
      """
      *........
      .........
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I flag cell at row 0, column 0
    And I chord reveal cell at row 1, column 0
    Then the cell at row 1, column 0 should not be revealed
    And the game state should be "playing"

  Scenario: Chord reveal hits mine and loses game
    Given the board is:
      """
      **.......
      .*.......
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I flag cell at row 0, column 1
    And I flag cell at row 2, column 0
    And I chord reveal cell at row 1, column 0
    Then the game state should be "lost"
    And the mine should be revealed

  Scenario: Chord reveal with mixed flagged and unflagged mines
    Given the board is:
      """
      *.*......
      .........
      *.*......
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I flag cell at row 2, column 0
    And I chord reveal cell at row 1, column 0
    Then the cell at row 1, column 1 should be revealed
    And the game state should be "playing"

  Scenario: Chord reveal that triggers auto-reveal
    Given the board is:
      """
      *........
      .........
      .........
      .........
      .........
      .........
      .........
      ......*.*
      ......*.*
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I chord reveal cell at row 1, column 0
    Then multiple cells should be revealed by auto-reveal
    And the game state should be "playing"

  Scenario: Chord reveal that wins the game
    Given the board is:
      """
      *.
      ..
      """
    When I set up the game with this board pattern
    And I reveal cell at row 1, column 0
    And I flag cell at row 0, column 0
    And I chord reveal cell at row 1, column 0
    Then the game state should be "won"
    And all cells should be revealed 
